image:
  file: .gitpod.Dockerfile
ports:
  - port: 8001
    onOpen: ignore
  - port: 3306
    onOpen: ignore
tasks:
  - init: cp .env.example .env && composer install && npm install && npm run dev && php artisan key:generate
    command: php artisan migrate --seed && php artisan serve
  - name: MySQL
    command: >
        mysqld
  - name: Apache
    command: >
        apachectl start;
        multitail /var/log/apache2/error.log -I /var/log/apache2/access.log
